### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by LoSilopante** [LoSilopante/create-air#2]

**Comment by Ghostipedia** [comment]
I've managed to update the Class and Mixin to behave with 1.20.1 would you like me to send that over?

I had troubles updating the build.gradle so I did a lot of this work within my own Coremod for my own modpack, but I'd be more than happy to PR it if you'd like

**Comment by LoSilopante** [comment]
@Ghostipedia Oh you've managed to make them work with the rewrite pf ThinAir? That's really nice! If you want to share them I'll add them right in.

**Comment by Ghostipedia** [comment]
Yup, here you go, me and my devs managed to get the Mixin working, the GUI status of the backtank working, and the mixin updated, feel free to take any code from our [CosmicCoreRemainingAirOverlayMixin.java](https://github.com/Ghostipedia/CosmicCore/blob/master/src/main/java/com/ghostipedia/cosmiccore/mixin/client/CosmicCoreRemainingAirOverlayMixin.java) [DivingHelmetItemMixin.java](https://github.com/Ghostipedia/CosmicCore/blob/master/src/main/java/com/ghostipedia/cosmiccore/mixin/DivingHelmetItemMixin.java) and/or [OxygenHelper.java](https://github.com/Ghostipedia/CosmicCore/blob/master/src/main/java/com/ghostipedia/cosmiccore/common/breath/OxygenHelper.java)

I'd like to take a moment to thank you for your initial work as it helped me figure out where I was going. :)
I apologize not making a PR directly as I'm still not very familiar with github and I don't want to risk damaging your repository!

Update ; We're experiencing some issues with the jar when built for normal clients (HUD Mixin is throwing a fit), I'll update this post once we resolve it


Update #2 okay fixed the  [CosmicCoreRemainingAirOverlayMixin.java](https://github.com/Ghostipedia/CosmicCore/blob/master/src/main/java/com/ghostipedia/cosmiccore/mixin/client/CosmicCoreRemainingAirOverlayMixin.java)
just had to remove `, remap=false` from the mixin location. all should be good now :)

**Comment by LoSilopante** [comment]
@Ghostipedia First of all I wish to thank you lot for the help provided, second I'm sorry for the late response, as I wasn't able to get to my PC 'till now; unfortunately when trying to implent RemainingAirOverlayMixin I've ran into some mixin problem leading to crash:
`"failed injection check, (0/1) succeeded. Scanned 1 target(s). No refMap loaded."`

**Comment by SeanChengN** [comment]
@LoSilopante Is there any progress?

**Comment by LoSilopante** [comment]
> @LoSilopante Is there any progress?

The update is live on curseforge, UI is still an issue.
