### ISSUE TITLE
Breaks create! 1.20.1

### ISSUE THREAD

**Issue by VolkianSoup** [LoSilopante/create-air#5]
When i open the game with this mod it breaks create and the addons for it!

**Comment by LoSilopante** [comment]
In what way? I just loaded up a profile with Create and a bunch of addons and there's no difference, Create Air or not.

**Comment by VolkianSoup** [comment]
> In what way? I just loaded up a profile with Create and a bunch of addons and there's no difference, Create Air or not.

Well I load it up with tons of Sedona and other mods and when I open my Minecraft it says create AllItems class can’t be found

**Comment by LoSilopante** [comment]
My mod doesn't even reference that, I think you have some other addon causing the problem.

**Comment by VolkianSoup** [comment]
No once I remove it the problem goes away even with just create and create air’s dependices
