### ISSUE TITLE
The tanks are not working.

### ISSUE THREAD

**Issue by itsglace1** [LoSilopante/create-air#6]
As said in the title. im wearing create backtanks both netherite and copper both straight up dont work. 1.20.1 1.0 version

**Comment by LoSilopante** [comment]
have you tested if they actually do not work, or if it is only the UI that doesn't work?
You should be able to stay underground with a backtank, you'd still see air dropping but once it "depletes" you should be set back to maximum.

**Comment by itsglace1** [comment]
i indeed did start taking damage. i thought it was a gui bug at first but guess not.

**Comment by itsglace1** [comment]
this happened in the nether btw. i did not test it in the overworld yet. i will do that tomorrow if u want me to

**Comment by itsglace1** [comment]
Deleting and redownloading worked
